import { defineConfig } from 'vite'
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

/**
 * Dev-only write endpoints backing the UI tools.
 *
 * The tools run in the page, so they cannot write files on their own — without
 * this, "save" could only mean localStorage, and the numbers would still have to
 * be hand-copied into a stylesheet to affect anything. This closes the loop:
 * a tool POSTs its document, and the server writes both a JSON record (the
 * source of truth the tool reopens) and a generated stylesheet the game loads.
 *
 * `apply: 'serve'` keeps the whole thing out of production builds; a shipped
 * game has no business exposing a file-writing route.
 */

/** POST a JSON body, get two files written. `render` may be null when the client sends its own CSS. */
function writeRoute({ route, json, css, render, count }) {
  return (server, root) => {
    const JSON_OUT = resolve(root, json)
    const CSS_OUT = resolve(root, css)
    server.middlewares.use(route, (req, res) => {
      if (req.method !== 'POST') {
        res.statusCode = 405
        res.end('POST only')
        return
      }
      let body = ''
      req.on('data', (chunk) => (body += chunk))
      req.on('end', () => {
        try {
          const parsed = JSON.parse(body)
          const [doc, sheet] = render ? [parsed, render(parsed)] : [parsed.json, parsed.css]
          if (typeof sheet !== 'string') throw new Error('no stylesheet in payload')
          mkdirSync(dirname(JSON_OUT), { recursive: true })
          writeFileSync(JSON_OUT, JSON.stringify(doc, null, 2))
          writeFileSync(CSS_OUT, sheet)
          res.setHeader('content-type', 'application/json')
          res.end(JSON.stringify({ ok: true, entries: count(doc) }))
        } catch (err) {
          res.statusCode = 400
          res.end(JSON.stringify({ ok: false, error: String(err) }))
        }
      })
    })
  }
}

/**
 * The legacy per-asset 9-slice tool at /slice.html.
 *
 * Rendered here rather than client-side because that page is plain static HTML
 * with no module graph to share a compiler with. The in-game editor supersedes
 * it and does not work this way.
 */
const renderSliceCss = (configs) => {
  const blocks = [
    '/*',
    ' * GENERATED by /slice.html — do not hand-edit.',
    ' *',
    ' * Per-*asset* slices. The in-game editor (F2) writes per-*element* ones to',
    ' * layout.generated.css, which loads after this and wins where they overlap.',
    ' */',
    '',
  ]
  for (const [file, c] of Object.entries(configs)) {
    if (!c.selectors) continue
    const fill = c.fill ? ' fill' : ''
    blocks.push(
      `/* ${file} */`,
      `${c.selectors} {`,
      `  border-style: solid;`,
      `  border-color: transparent;`,
      `  border-width: ${c.bt}px ${c.br}px ${c.bb}px ${c.bl}px;`,
      `  border-image: url('${file}') ${c.t} ${c.r} ${c.b} ${c.l}${fill} ${c.repeat};`,
      ...(c.outset ? [`  border-image-outset: ${c.outset}px;`] : []),
      `}`,
      '',
    )
  }
  return blocks.join('\n')
}

function uiToolServer() {
  const root = process.cwd()
  const routes = [
    writeRoute({
      route: '/__nine-slice',
      json: 'public/ui/nine-slice.json',
      css: 'public/ui/nine-slice.generated.css',
      render: renderSliceCss,
      count: (c) => Object.keys(c).length,
    }),
    /*
     * The layout editor sends `{json, css}` and this route writes both verbatim.
     *
     * Re-implementing docToCss here was the obvious alternative and the wrong
     * one: this file is plain JS loaded before any TS transform exists, so a
     * second copy of the compiler could never import the tested one, and the
     * stylesheet on disk would be free to drift from the live preview the editor
     * showed. Letting the client render it makes them the same bytes by
     * construction.
     */
    writeRoute({
      route: '/__ui-layout',
      json: 'public/ui/layout.json',
      css: 'public/ui/layout.generated.css',
      render: null,
      count: (d) => (d?.entries ?? []).length,
    }),
  ]
  return {
    name: 'ui-tool-server',
    apply: 'serve',
    configureServer(server) {
      for (const mount of routes) mount(server, root)
    },
  }
}

/**
 * Re-base `url(/ui/…)` in the bundled CSS so a build survives a subdirectory.
 *
 * The stylesheet references art in `public/`, which vite deliberately does not
 * process or rewrite — the documented way to point at it is an absolute path.
 * That path is correct in dev, where the sheet is served from `/src/ui/` and the
 * art from `/ui/`, and wrong in a build served from anywhere but a domain root,
 * where the leading slash resolves against the host and every button loses its
 * face.
 *
 * Writing `../ui/…` in the source instead trades one for the other: right for
 * the bundle at `assets/`, broken in dev. There is no single literal that is
 * correct in both, because the sheet lives at a different depth in each. So the
 * source stays dev-correct and the *output* is rewritten here — one rule, in one
 * place, that fires only for the build.
 */
function publicUrlsRelative() {
  return {
    name: 'public-urls-relative',
    apply: 'build',
    generateBundle(_options, bundle) {
      for (const file of Object.values(bundle)) {
        if (file.type !== 'asset' || !file.fileName.endsWith('.css')) continue
        // Bundled CSS lands in assets/, one level below the art in ui/.
        file.source = String(file.source).replace(/url\((['"]?)\/(ui|textures)\//g, 'url($1../$2/')
      }
    },
  }
}

export default defineConfig({
  plugins: [uiToolServer(), publicUrlsRelative()],
  /*
   * Relative, not absolute. A host that serves the build from a subdirectory or
   * a CDN resolves `/assets/index.js` against its own root and 404s — the zip
   * has to reference its assets relative to index.html, and it must also run
   * straight off the filesystem. build-web.bat fails the build if this regresses.
   */
  base: './',
  server: {
    port: 5214,
    strictPort: true,
  },
  build: {
    /*
     * Boot uses top-level await (asset preload, save restore), which is an
     * ES2022 feature. Vite's default es2020 target refuses it at
     * build time even though every browser this game targets (and the dev
     * server) runs it fine.
     */
    target: 'es2022',
  },
})
