/**
 * The layout document: what the editor writes, what the game reads.
 *
 * Kept free of DOM calls on purpose. Compiling a document to CSS is the one
 * piece of this system that decides what the game actually looks like, so it is
 * a pure string function that can be tested without a browser — the alternative
 * is discovering a bad rule by looking at the screen and guessing.
 */

import { cssText, rectToCss, type RectTransform } from './rect'
import { scoped } from './keys'

/** Per-element 9-slice. Same fields the old per-asset tool used, so its saved values port straight over. */
export interface SliceData {
  /** Absolute URL of the source image, e.g. `/ui/btn-green.png`. */
  src: string
  /** Source slice inset, px. */
  t: number
  r: number
  b: number
  l: number
  /** Rendered border width, px. Equal to the slice at "power 1". */
  bt: number
  br: number
  bb: number
  bl: number
  fill: boolean
  repeat: 'stretch' | 'repeat' | 'round' | 'space'
  outset: number
}

export interface LayoutEntry {
  /** CSS selector, unscoped. Widen it by hand to style a whole class of widget. */
  selector: string
  /** Human label, for the editor's lists. Never affects output. */
  label?: string
  rect?: RectTransform
  slice?: SliceData
  /** Escape hatch for declarations the structured fields do not cover. */
  css?: Record<string, string>
}

export interface LayoutDoc {
  version: 1
  entries: LayoutEntry[]
}

export const EMPTY_DOC: LayoutDoc = { version: 1, entries: [] }

/**
 * Slice art, addressed relative to the stylesheet this ends up in.
 *
 * The compiled sheet is written to `public/ui/`, so a bare filename resolves
 * beside it. An absolute `/ui/x.png` — which is what the editor used to store —
 * resolves against the *host* root instead, and a build served from a
 * subdirectory on a portal CDN then 404s every piece of UI art it references.
 * Legacy documents are normalised here rather than migrated, so an old
 * layout.json keeps working without a rewrite step.
 */
function sliceUrl(src: string) {
  return src.replace(/^\/?ui\//, '')
}

export function sliceCss(s: SliceData): Record<string, string> {
  const out: Record<string, string> = {
    'border-style': 'solid',
    'border-color': 'transparent',
    'border-width': `${s.bt}px ${s.br}px ${s.bb}px ${s.bl}px`,
    'border-image': `url('${sliceUrl(s.src)}') ${s.t} ${s.r} ${s.b} ${s.l}${s.fill ? ' fill' : ''} ${s.repeat}`,
  }
  if (s.outset) out['border-image-outset'] = `${s.outset}px`
  return out
}

/**
 * Compile a document to a stylesheet.
 *
 * Entry order is preserved and becomes cascade order, so a later broad entry can
 * deliberately sit on top of an earlier narrow one. Entries with nothing to say
 * are dropped rather than emitted as empty rules — an empty rule is invisible in
 * the output but still a selector the browser has to match on every restyle.
 */
export function docToCss(doc: LayoutDoc): string {
  const out: string[] = [
    '/*',
    ' * GENERATED by the in-game UI editor (F2) — do not hand-edit.',
    ' *',
    ' * Every selector is scoped under #ui, which is how these rules outrank the',
    ' * hand-written ones in styles.css without needing !important.',
    ' */',
    '',
  ]
  for (const entry of doc.entries) {
    if (!entry.selector?.trim()) continue
    const decls: Record<string, string> = {}
    if (entry.rect) Object.assign(decls, rectToCss(entry.rect))
    if (entry.slice) Object.assign(decls, sliceCss(entry.slice))
    if (entry.css) Object.assign(decls, entry.css)
    if (!Object.keys(decls).length) continue
    if (entry.label) out.push(`/* ${entry.label} */`)
    out.push(`${scoped(entry.selector)} {`, cssText(decls), '}', '')
  }
  return out.join('\n')
}

/** Find an entry by selector, or undefined. Selector is the identity. */
export function findEntry(doc: LayoutDoc, selector: string): LayoutEntry | undefined {
  return doc.entries.find((e) => e.selector === selector)
}

/** Insert or replace an entry, returning a new document. */
export function upsertEntry(doc: LayoutDoc, entry: LayoutEntry): LayoutDoc {
  const i = doc.entries.findIndex((e) => e.selector === entry.selector)
  const entries = doc.entries.slice()
  if (i >= 0) entries[i] = entry
  else entries.push(entry)
  return { ...doc, entries }
}

export function removeEntry(doc: LayoutDoc, selector: string): LayoutDoc {
  return { ...doc, entries: doc.entries.filter((e) => e.selector !== selector) }
}

/**
 * Accept a parsed JSON blob as a document, or fall back to empty.
 *
 * A missing or malformed file must never stop the game booting: the layout
 * overrides are a convenience on top of a stylesheet that already works, so the
 * correct response to garbage on disk is to ignore it, not to throw in `main`.
 */
export function parseDoc(raw: unknown): LayoutDoc {
  if (!raw || typeof raw !== 'object') return EMPTY_DOC
  const entries = (raw as LayoutDoc).entries
  if (!Array.isArray(entries)) return EMPTY_DOC
  return {
    version: 1,
    entries: entries.filter(
      (e): e is LayoutEntry => !!e && typeof e === 'object' && typeof e.selector === 'string',
    ),
  }
}
